#
# Simulator config
#

max_wind_speed: 0.0

# Possible values: "random", "north", "east", "south", "west" and empty string
wind_direction: "north"

#Possible values: "random", "max"
wind_amplitude: "max"
